blog_flask/posts/forms.py
"""Posts forms"""


from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, TextAreaField, SubmitField, FileField
from wtforms.validators import DataRequired, ValidationError, Length

from blog_flask.models import User, Post


class PostCreateForm(FlaskForm):
    """Creation form"""

    title = StringField(
        label='Заголовок',
        validators=[
            DataRequired(),
            Length(min=1, max=100)
        ]
    )
    content = TextAreaField(
        label='Содержание',
        validators=[DataRequired()]
    )
    picture = FileField(
        label='Добавить изображение',
        validators=[FileAllowed(['png', 'jpg'])]
    )
    submit = SubmitField('Опубликовать')


class CommentForm(FlaskForm):
    """Create comment form"""

    content = TextAreaField(
        label='Комментарий',
        validators=[
            DataRequired()
        ],
    )
    submit = SubmitField('Комментировать')

blog_flask/posts/routes.py
"""Posts controllers"""
import datetime
import json

from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from sqlalchemy import or_, and_

from blog_flask.users.utils import save_picture
from blog_flask.models import Post, Comment, Images, Like
from blog_flask.posts.forms import PostCreateForm, CommentForm


posts = Blueprint('posts', __name__, url_prefix='/posts')


@posts.route('/allpost', methods=['GET', 'POST'])
@login_required
def allpost():
    """Controller for list of all posts"""
    page = request.args.get('page', 1, type=int)
    search = request.args.get('search', None, type=str)
    favorites = request.args.get('favorites', 0, type=int)
    if favorites:
        posts_list = Post.query.join(
            Like, Like.post_id == Post.id
        ).filter(
            Like.user == current_user
        ).order_by(
            Post.created_at.desc()
        ).paginate(
            page=page, per_page=5
        )
    elif search:
        posts_list = Post.query.filter(
            or_(
                Post.title.contains(search),
                Post.content.contains(search)
            )
        ).order_by(
            Post.created_at.desc()
        ).paginate(
            page=page, per_page=5
        )
    else:
        posts_list = Post.query.order_by(Post.created_at.desc()).paginate(
            page=page, per_page=5
        )
    return render_template('allpost.html', posts=posts_list)


@posts.route('/publish', methods=['GET', 'POST'])
@login_required
def publish():
    """Controller to create new post"""
    form = PostCreateForm()
    if form.validate_on_submit():
        post_item = Post(
            title=form.title.data,
            content=form.content.data,
            created_at=datetime.datetime.utcnow(),
            author=current_user
        )
        if form.picture.data:
            img = save_picture(form.picture.data, post=True)
            image_obj = Images(
                post=post_item,
                content=img,
                created_at=datetime.datetime.now()
            )
            image_obj.save()
        else:
            post_item.save()
        flash('Опубликовано', 'success')
        return redirect(url_for('posts.allpost'))
    return render_template('create_post.html', title='Новый пост', form=form)


@posts.route('/post')
def post():
    """Post detail page"""
    post_id = request.args.get('post_id', 0, type=int)
    post_item = Post.query.get_or_404(post_id)
    form = CommentForm()
    post_item.comments.sort(key=lambda x: x.created_at, reverse=True)
    likes = len(list(post_item.likes))
    liked = bool(Like.query.filter(
        and_(
            Like.post == post_item,
            Like.user == current_user
        )
    ).count())
    return render_template('post.html', post=post_item, form=form, likes=likes, liked=liked)


@posts.route('/update', methods=['GET', 'POST'])
@login_required
def update_post():
    """Update post"""
    post_id = request.args.get('post_id', 0, type=int)
    post_item = Post.query.get_or_404(post_id)
    if post_item.author != current_user:
        abort(403)
    form = PostCreateForm()
    if form.validate_on_submit():
        post_item.content = form.content.data
        post_item.title = form.title.data
        if form.picture.data:
            img = save_picture(form.picture.data, post=True)
            image_obj = Images(
                post=post_item,
                content=img,
                created_at=datetime.datetime.now()
            )
            image_obj.save()
        else:
            post_item.save()
        flash('Обновлено', 'success')
        return redirect(url_for('posts.post', post_id=post_id))
    elif request.method == 'GET':
        form.title.data = post_item.title
        form.content.data = post_item.content
    return render_template('create_post.html', title='Обновление поста', form=form, legend='Обновление поста')


@posts.route('/delete', methods=['POST'])
@login_required
def delete_post():
    """Delete post"""
    post_id = request.args.get('post_id', 0, type=int)
    post_item = Post.query.filter(Post.id == post_id).one_or_none()
    if post_item is None or post_item.author != current_user:
        abort(403)
    post_item.delete()
    flash('Пост удален', 'success')
    return redirect(url_for('posts.allpost'))


@posts.route('/comment', methods=['POST'])
@login_required
def comment():
    """Add comment"""
    post_id = request.args.get('post_id', 0, type=int)
    post_item = Post.query.filter(Post.id == post_id).one_or_none()
    if post_item is None:
        abort(404)
    form = CommentForm()
    if form.validate_on_submit():
        comment_obj = Comment(
            content=form.content.data,
            created_at=datetime.datetime.now(),
            author=current_user,
            post=post_item
        )
        comment_obj.save()
        flash('Успешно!', 'success')
        return redirect(url_for('posts.post', post_id=post_item.id))


@posts.route('/edit_comment', methods=['GET', 'POST'])
@login_required
def edit_comment():
    """Edit comment"""
    comment_id = request.args.get('comment_id', 0, type=int)
    comment_item = Comment.query.filter(Comment.id == comment_id).one_or_none()
    if comment_item is None:
        abort(404)
    if comment_item.author != current_user:
        abort(403)
    edit_form = CommentForm()
    if edit_form.validate_on_submit():
        comment_item.content = edit_form.content.data
        comment_item.created_at = datetime.datetime.now()
        comment_item.save()
        flash('Обновлено!', 'success')
        return redirect(url_for('posts.post', post_id=comment_item.post.id))
    edit_form.content.data = comment_item.content
    form = CommentForm()
    comment_item.post.comments.sort(key=lambda x: x.created_at, reverse=True)
    return render_template('post.html', post=comment_item.post, form=form, edit_form=edit_form, comment_id=comment_id)


@posts.route('/delete_comment', methods=['POST'])
@login_required
def delete_comment():
    """Delete comment"""
    comment_id = request.args.get('comment_id', 0, type=int)
    comment_item = Comment.query.filter(Comment.id == comment_id).one_or_none()
    post_id = comment_item.post_id
    if comment_item is None:
        abort(404)
    if comment_item.author != current_user:
        abort(403)
    comment_item.delete()
    return redirect(url_for('posts.post', post_id=post_id))


@posts.route('/like', methods=['POST'])
@login_required
def like():
    """set/remove users like"""
    post_id = request.args.get('post_id', 0, type=int)
    post_item: Post = Post.query.filter(Post.id == post_id).one_or_none()
    count = len(list(post_item.likes))
    post_like = Like.query.filter(
        and_(
            Like.post == post_item,
            Like.user == current_user
        )
    ).one_or_none()
    if post_like:
        post_like.delete()
        return json.dumps({
            'status': 'ok',
            'likes': count - 1
        })

    post_like = Like(
        user=current_user,
        post=post_item
    )
    post_like.save()
    return json.dumps({
        'status': 'ok',
        'likes': count + 1
    })

blog_flask/users/routes.py
"""Usersapp controllers"""

from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required

from blog_flask import db, bcrypt
from blog_flask.models import User, Post
from blog_flask.users.forms import RegistrationForm, LoginForm, UserProfileUpdateForm, ChangePasswordRequestForm, \
    ChangePasswordForm
from blog_flask.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    """Users registration controller"""
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=hashed_password
        )
        user.save()
        flash("Регистрация прошла успешно", "success")
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    """User login controller"""
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).one_or_none()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            return redirect(url_for('posts.allpost'))
        else:
            flash('Не верный логин и/или пароль', 'Внимание')
    return render_template('login.html', title='Авторизация', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UserProfileUpdateForm()
    if form.validate_on_submit():
        if form.avatar.data:
            avatar_file = save_picture(form.avatar.data)
            current_user.avatar = avatar_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Обновлено!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(
            username=form.username.data
        ).first_or_404()
        posts = Post.query.filter_by(
            author=user
        ).order_by(
            Post.created_at.desc()
        ).paginate(page=page, per_page=5)
        image_file = url_for('static', filename='profile_pictures/' + current_user.avatar)
        return render_template(
            'account.html',
            title='Account',
            image_file=image_file,
            form=form,
            posts=posts,
            user=user
        )


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/user_posts')
def user_posts():
    username = request.args.get('username', type=str)
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first()
    posts = Post.query.filter_by(author=user).order_by(
        Post.created_at.desc()
    ).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    """Password remainder"""
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    form = ChangePasswordRequestForm()
    if form.validate_on_submit():
        token = form.user.get_reset_token()
        send_reset_email(token, form.user.email)
        flash("На указанные адрес было направлено письмо со ссылкой на изменение пароля", 'info')
        return redirect(url_for('users.login'))
    return render_template('forgot_password.html', title='Восстановление пароля', form=form)


@users.route('/change_password', methods=['GET', 'POST'])
def change_password():
    """Change users password"""
    form = ChangePasswordForm()
    if request.method == 'GET':
        token = request.args.get('token', None, type=str)
        user = User.verify_reset_token(token)
        if not user:
            flash('Не правильный/истекший токен', 'error')
            return redirect(url_for('users.forgot_password'))
        return render_template('change_password.html', title='Смена пароля', form=form, user=user)
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user_id = request.args.get('user_id', type=int)
        user = User.query.get(user_id)
        user.password = hashed_password
        user.save()
        flash('Успешно!',  'success')
        return redirect(url_for('users.login'))

blog_flask/templates/allpost.html
{% extends "layout.html" %}
{% block content %}
  {% for post in posts.items %}
  <div class="content-card">
    <div class="card-author">
      <img class="article-img" src="{{ url_for('static', filename='profile_pictures/' + post.author.avatar) }}">
      <a class="navbar-user card-title card-author" href="{{ url_for('users.user_posts', username=post.author.username) }}" id="author">{{ post.author.username }}</a>
    </div>
    
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><a class="navbar-user card-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>
        <small>Опубликовано {{ post.created_at.strftime('%A, %d %B %Y %I:%M %p') }}</small>
        <div class="likes">
          <i class="fa fa-heart heart heart-red small-heart" aria-hidden="true"></i>
          <span class="small-heart">{{ post.likes | length }}</span>
          <span class="small-heart">&#9997; {{ post.comments | length }}</span>
        </div>
        <p class="card-text">{{ post.content }}</p>
      </div>
    </div>
  </div>
  {% endfor %}
  <div class="pagination">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="paginate-button selected-page" href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="paginate-button" href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}
  </div>
{% endblock content %}

blog_flask/templates/change_password.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section" style="box-shadow: 10px 15px 10px #4a4e69;">
        <form method="POST" action="{{ url_for('users.change_password', user_id=user.id) }}">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Восстановление пароля</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="action-button ok") }}
                <a href="{{ url_for('users.login') }}" class="action-button notok">Назад</a>
            </div>
            <small style="font-size: 15px; font-weight: 500;">
                Нужен аккаунт? <a class="ml-2" href="{{ url_for('users.register') }}">Зарегистрируйтесь</a>
            </small>
        </form>
    </div>
{% endblock content %}

blog_flask/templates/forgot_password.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Восстановление пароля</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="action-button ok") }}
                <a href="{{ url_for('users.login') }}" class="action-button notok">Назад</a>
            </div>
            <small style="font-size: 15px; font-weight: 500;">
                Нужен аккаунт? <a class="ml-2" href="{{ url_for('users.register') }}">Зарегистрируйтесь</a>
            </small>
        </form>
    </div>
{% endblock content %}

blog_flask/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Stalinist+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/css/font-awesome.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/css/font-awesome.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Flask-блог - {{ title }}</title>
    {% else %}
        <title>Flask-блог</title>
    {% endif %}

    {% block head %} {% endblock head %}
  {% block style %} {% endblock style %}
</head>
<body>
    <div class="body">
        <div class="wrapper">
          <div class="navbar">
            <div class="navbar-main">
                <a class="navbar-brand" href="/">Диалоги о рыбалке</a>
            </div>
            <div class="navbar-profile">
                {% if current_user.is_authenticated %}
                    <h4 class="navbar-user">Привет, {{ current_user.username }}!</h4>
                    <a href="{{ url_for('users.account') }}" class="nav-link nav-item navigation-links">
                        Аккаунт
                    </a>
                    <a href="{{ url_for('users.logout') }}" class="nav-link nav-item navigation-links">
                        Выйти
                    </a>
                {% else %}
                    <a href="{{ url_for('users.register') }}" class="nav-link nav-item navigation-links">
                        Зарегистрироваться
                    </a>
                    <a href="{{ url_for('users.login') }}" class="nav-link nav-item navigation-links">
                        Войти
                    </a>
                {% endif %}
            </div>
          </div>
            <ul class="menu">
                <li>
                    <a href="{{ url_for('posts.allpost') }}" class="nav-link nav-item navigation-links">
                        Все посты
                    </a>
                </li>
                <li>
                    <form class="search" action="{{ url_for('posts.allpost') }}" method="get">
                        {{ search.search(class="search-input", placeholder="Введите текст для поиска...") }}
                        {{ search.find(class="search-button") }}
                    </form>
                </li>
                {% if current_user.is_authenticated %}
                <li>
                    <a href="{{ url_for('posts.publish') }}" class="nav-link nav-item navigation-links">
                        Новый пост
                    </a>
                </li>
                <li>
                    <a href="{{ url_for('posts.allpost', favorites=1) }}" class="nav-link nav-item navigation-links">
                        Избранное
                    </a>
                </li>
                {% endif %}
            </ul>
            <div class="content">
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                  {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                      {{ message }}
                    </div>
                  {% endfor %}
                {% endif %}
              {% endwith %}
              {% block content %}{% endblock %}
            </div>
        </div>
        <div class="footer">
            &copy; SMozheiko {{ year }}
        </div>
    </div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% block js %}
{% endblock %}
</body>
</html>

blog_flask/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Авторизация</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="action-button ok") }}
            </div>
            <small style="font-size: 15px; font-weight: 500;">
                Нужен аккаунт? <a class="ml-2" href="{{ url_for('users.register') }}">Зарегистрируйтесь</a>
            </small>
        </form>
        <div class="forgot-password">
            <a href="{{ url_for('users.forgot_password') }}" class="forgot-password-link">Не помню пароль</a>
        </div>
    </div>
{% endblock content %}

blog_flask/templates/post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-card">
  <div class="card-author">
    <img class="article-img" src="{{ url_for('static', filename='profile_pictures/' + post.author.avatar) }}">
    <a class="navbar-user card-title card-author" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
  </div>
  
  <div class="card">
    <div class="card-body">
      <h4 class="navbar-user card-title" style="margin: 0 20px">{{ post.title }}</h4>
      <small>Опубликовано {{ post.created_at.strftime('%A, %d %B %Y %I:%M %p') }}</small>
      <br>
      <br>
      <p class="card-text">
          {% if post.images %}
            <div class="post-images">
                {% for image in post.images %}
                <img class="post-image" src="{{ url_for('static', filename='post_pictures/' + image.content) }}" data-id="{{ image.id }}" alt="image">
                {% endfor %}
            </div>
          {% endif %}
          {{ post.content }}
      </p>
    </div>
      <div class="card-footer">
        {% if post.author == current_user %}
          <a class="action-button ok" href="{{url_for('posts.update_post', post_id=post.id) }}">Обновить</a>
          <button type="button" class="action-button notok" data-toggle="modal" data-target="#deleteModal">Удалить</button>
        {% endif %}
          <i class="fa fa-heart heart{% if liked %} heart-red{% endif %}" aria-hidden="true" data-url="{{ url_for('posts.like', post_id=post.id) }}"></i>
          <span class="likes-count">{{ likes }}</span>
      </div>
    <form action="{{ url_for('posts.comment', post_id=post.id) }}" method="post">
      {{ form.hidden_tag() }}
        <div class="comment-form">
            <h3>{{ form.content.label(class="comments-small-title") }}</h3>
            {% if form.content.errors %}
                {{ form.content(class="comment-content is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.content(class="comment-content", rows=10, cols=80) }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.submit(class="action-button ok") }}
        </div>
    </form>
    <h3 class="comments-title">{% if post.comments %}Все комментарии{% else %}Комментариев пока нет{% endif %}</h3>
    <ul class="card-comments">
      {% for comment in post.comments %}
      {% if not comment_id or comment.id != comment_id %}
      <li class="card-comment">
        <div class="comment-author">
          <a class="navbar-user card-title card-author" href="{{ url_for('users.user_posts', username=comment.author.username) }}">{{ comment.author.username }}</a>
          {% if comment.author == current_user %}
          <a href="{{ url_for('posts.edit_comment', comment_id=comment.id) }}">&#9997;</a>
          <button class="delete-comment" data-action="{{ url_for('posts.delete_comment', comment_id=comment.id) }}">&#10060;</button>
          {% endif %}
        </div>
        <small class="comment-date">
          {{ comment.created_at }}
        </small>
        <div class="comment-content">
          {{ comment.content }}
        </div>
      </li>
      {% else %}
      <form class="card-comment" action="{{ url_for('posts.edit_comment', comment_id=comment.id) }}" method="post">
        {{ edit_form.hidden_tag() }}
          <div>
              <h3>Редактирование</h3>
              {% if edit_form.content.errors %}
                  {{ edit_form.content(class="comment-content is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in edit_form.content.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ edit_form.content(class="comment-content", rows=10, cols=80) }}
              {% endif %}
          </div>
          <div class="form-group">
              {{ edit_form.submit(class="action-button ok", value='Сохранить') }}
          </div>
      </form>
        {% endif %}
      {% endfor %}
    </ul>
  </div>
</div>
  
<!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Удалить пост?</h5>
        </div>
        <div class="modal-footer">
          <button type="button" class="action-button ok" data-dismiss="modal">Отмена</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="action-button notok" type="submit" value="Удалить">
          </form>
        </div>
      </div>
    </div>
  </div>
    <div class="modal" id="delete-comment-modal" tabindex="-1" aria-hidden="true" hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Удалить комментарий?</h5>
            </div>
            <form id="delete-comment-form" class="modal-footer" action="" method="post">
                <button type="button" class="action-button ok" data-dismiss="modal">Отмена</button>
                <input class="action-button notok" type="submit" value="Удалить">
            </form>
          </div>
        </div>
    </div>
{% endblock content %}
{% block js %}
<script src="{{ url_for('static', filename='js/post.js') }}"></script>
{% endblock %}